# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField(default=0, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('manager_id', models.CharField(max_length=30)),
                ('operational_unit', models.CharField(max_length=30)),
                ('performance_rating', models.IntegerField()),
                ('potential_rating', models.IntegerField()),
                ('assignment', models.CharField(choices=[('Adm', 'Administration/FrontDesk'), ('Bus', 'Business Office'), ('Mgm', 'Management')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vative.Employees', unique=True)),
            ],
        ),
    ]
